alter session set "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER "Backend" IDENTIFIED BY "12345"  ;

-- QUOTAS
ALTER USER "Backend" QUOTA 307200k ON "USERS";

-- ROLES
GRANT "CONNECT" TO "Backend" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "Backend" WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "Backend" ;
GRANT DROP ANY CONTEXT TO "Backend" ;
GRANT UPDATE ANY CUBE TO "Backend" ;
GRANT ALTER ANY ANALYTIC VIEW TO "Backend" ;
GRANT DROP ANY TRIGGER TO "Backend" ;
GRANT DROP ANY SQL TRANSLATION PROFILE TO "Backend" ;
GRANT MANAGE ANY FILE GROUP TO "Backend" ;
GRANT ALTER PUBLIC DATABASE LINK TO "Backend" ;
GRANT MANAGE FILE GROUP TO "Backend" ;
GRANT ALTER ANY INDEX TO "Backend" ;
GRANT DROP ANY SEQUENCE TO "Backend" ;
GRANT ALTER PROFILE TO "Backend" ;
GRANT INHERIT ANY PRIVILEGES TO "Backend" ;
GRANT UNDER ANY TABLE TO "Backend" ;
GRANT CREATE ASSEMBLY TO "Backend" ;
GRANT DROP ANY LIBRARY TO "Backend" ;
GRANT ALTER ANY EDITION TO "Backend" ;
GRANT CREATE ROLE TO "Backend" ;
GRANT CREATE LIBRARY TO "Backend" ;
GRANT DROP ROLLBACK SEGMENT TO "Backend" ;
GRANT CREATE TRIGGER TO "Backend" ;
GRANT ALTER ANY PROCEDURE TO "Backend" ;
GRANT ADMINISTER DATABASE TRIGGER TO "Backend" ;
GRANT DROP ANY MEASURE FOLDER TO "Backend" ;
GRANT CREATE ANY PROCEDURE TO "Backend" ;
GRANT ALTER ANY OUTLINE TO "Backend" ;
GRANT CREATE ANY ANALYTIC VIEW TO "Backend" ;
GRANT EXECUTE ANY INDEXTYPE TO "Backend" ;
GRANT USE ANY JOB RESOURCE TO "Backend" ;
GRANT CREATE ANY DIRECTORY TO "Backend" ;
GRANT ALTER ANY RULE SET TO "Backend" ;
GRANT USE ANY SQL TRANSLATION PROFILE TO "Backend" ;
GRANT ALTER ANY MINING MODEL TO "Backend" ;
GRANT DEBUG CONNECT SESSION TO "Backend" ;
GRANT LOGMINING TO "Backend" ;
GRANT DROP ANY ATTRIBUTE DIMENSION TO "Backend" ;
GRANT CREATE ANY MINING MODEL TO "Backend" ;
GRANT CREATE LOCKDOWN PROFILE TO "Backend" ;
GRANT ALTER SESSION TO "Backend" ;
GRANT CREATE MATERIALIZED VIEW TO "Backend" ;
GRANT CREATE PLUGGABLE DATABASE TO "Backend" ;
GRANT DROP ANY ANALYTIC VIEW TO "Backend" ;
GRANT WRITE ANY ANALYTIC VIEW CACHE TO "Backend" ;
GRANT MERGE ANY VIEW TO "Backend" ;
GRANT CREATE ANY INDEX TO "Backend" ;
GRANT READ ANY ANALYTIC VIEW CACHE TO "Backend" ;
GRANT CREATE DIMENSION TO "Backend" ;
GRANT EXECUTE ANY RULE SET TO "Backend" ;
GRANT CREATE SQL TRANSLATION PROFILE TO "Backend" ;
GRANT ALTER ANY MATERIALIZED VIEW TO "Backend" ;
GRANT AUDIT SYSTEM TO "Backend" ;
GRANT CREATE OPERATOR TO "Backend" ;
GRANT MANAGE ANY QUEUE TO "Backend" ;
GRANT ALTER ANY SQL PROFILE TO "Backend" ;
GRANT GRANT ANY OBJECT PRIVILEGE TO "Backend" ;
GRANT CREATE INDEXTYPE TO "Backend" ;
GRANT AUDIT ANY TO "Backend" ;
GRANT INHERIT ANY REMOTE PRIVILEGES TO "Backend" ;